[package]
name = "bs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7"
inkwell = { version = "0.2.0", features = ["llvm13-0"] }
